export const data = [
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
  { icon: '', tag: '어깨' },
]
